const ACTIONS = {
  WEAKEN_SECURITY: "WEAKEN_SECURITY",
  GROW_MONEY: "GROW_MONEY",
  STEAL_MONEY: "STEAL_MONEY",
  DO_NOTHING: "DO_NOTHING"
}

const GROW_TARGET = 0.9
const MINIMUM_CASH = 0.1
const HOME_RESERVED_RAM = 50

export { ACTIONS, GROW_TARGET, MINIMUM_CASH, HOME_RESERVED_RAM }
